### ISSUE TITLE
Active record features

### ISSUE THREAD

**Issue by PinkaminaDianePie** [planck/planck#19]
Need to provide following features for the first working version of ActiveRecord and mongodb driver.
- [x] Saving new in-memory object in db
- [ ] Saving array of new in-memory objects in db
- [x] Saving existed in-memory object in db (updating)
- [ ] Creating new object in db
- [ ] Selecting existed object by id
- [ ] Selecting existed object by complex filter
- [ ] Selecting array of existed objects by their id's
- [ ] Selecting array of existed objects by their id's
- [ ] Selecting array of existed objects by complex filters
- [ ] Deleting existed object by id
- [ ] Pagination (skip+limit)
- [ ] Foreign keys for one-to-many links, CRUD for separate tables
- [ ] Foreign keys for one-to-many links, CRUD for denormalized objects
